version: '3'

services:
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn start"
    deploy:
       restart_policy:
        condition: on-failure
        max_attempts: 2
    volumes:
      - .:/usr/app
    # when network_mode === 'host', the 'localhost' inside the container
    # is the same 'localhost' in the machine,
    # which means every redirection to exposed ports will work (see index.js)
    network_mode: host